version: '3'
services:
    identidock:
        image: syt0438/study-docker-identidock:latest
        ports:
            - '5000:5000'
        environment:
            ENV: DEV
        volumes:
            - ./app:/app
        links:
            - dnmonster:dnmonster
            - redis:redis

    dnmonster:
        image: amouat/dnmonster:1.0
        ports:
            - '8080:8080'

    redis:
        image: redis
